#!/bin/bash -e

dotnet restore
dotnet build FsiRefGen.sln

if hash mono &> /dev/null ; then
  RUN=mono
else
  RUN=
fi

for TEMPLATE in *.paket.template ; do
  $RUN .paket/paket.exe --silent pack output . --template "$TEMPLATE"
done
