#!/bin/bash -e -x

DIR="$(dirname "$0")"
PROJECT="${PROJECT:-$DIR/src/FsiRefGen.fsproj}"

if ! [ -f "$PROJECT" ] ; then
  pushd "$DIR"
  ./build
  popd
fi

dotnet run --framework net6.0 --project "$PROJECT" -- "$@"
