#!/bin/bash -e

if hash mono &> /dev/null ; then
  RUN=mono
fi

DIR="$(dirname "$0")"
EXE="$DIR/src/bin/Release/FsiRefGen.exe"

if ! [ -f "$EXE" ] ; then
  pushd "$DIR"
  ./build
  popd
fi

$RUN "$EXE" "$@"
